---

- name: restart httpd
  service: name=httpd state=restarted

- name: reload httpd
  service: name=httpd state=reloaded

- name: validate httpd
  shell: httpd -t

- name: validate and restart httpd
  shell: httpd -t
  notify: restart httpd

- name: validate and reload httpd
  shell: httpd -t
  notify: reload httpd
